/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "G:\\Project\\vuePress\\vue-press\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1765e050",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1765e050").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-34e90491",
    path: "/Web/Command/other.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34e90491").then(next)
    },
  },
  {
    name: "v-fc6220b4",
    path: "/language/chinese/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fc6220b4").then(next)
    },
  },
  {
    path: "/language/chinese/index.html",
    redirect: "/language/chinese/"
  },
  {
    name: "v-72d8270e",
    path: "/Web/Command/Typora.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72d8270e").then(next)
    },
  },
  {
    name: "v-53c6c9bf",
    path: "/language/chinese/b.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53c6c9bf").then(next)
    },
  },
  {
    name: "v-e934e4f4",
    path: "/language/english/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e934e4f4").then(next)
    },
  },
  {
    path: "/language/english/index.html",
    redirect: "/language/english/"
  },
  {
    name: "v-cea56c42",
    path: "/frontWeb/%E5%89%8D%E7%AB%AF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cea56c42").then(next)
    },
  },
  {
    path: "/frontWeb/前端.html",
    redirect: "/frontWeb/%E5%89%8D%E7%AB%AF.html"
  },
  {
    path: "/frontWeb/前端.html",
    redirect: "/frontWeb/%E5%89%8D%E7%AB%AF.html"
  },
  {
    name: "v-d347a8e6",
    path: "/Web/Css/01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d347a8e6").then(next)
    },
  },
  {
    name: "v-6140e9c1",
    path: "/language/chinese/a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6140e9c1").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]