/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Hello VuePress",
  "description": "Just playing around",
  "base": "/vuepress-doc/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/vuepress-doc/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "前端博客,个人技术博客,前端,前端开发,前端框架,web前端,前端面试题,技术文档,学习,面试,JavaScript,js,ES6,TypeScript,vue,python,css3,html5,Node,git,github,markdown"
      }
    ],
    [
      "meta",
      {
        "name": "baidu-site-verification",
        "content": "7F55weZDDc"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#11a8cd"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "script",
      {
        "language": "javascript",
        "type": "text/javascript",
        "src": "https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1765e050",
      "path": "/"
    },
    {
      "title": "git常用命令",
      "frontmatter": {},
      "regularPath": "/Web/Command/other.html",
      "relativePath": "Web/Command/other.md",
      "key": "v-34e90491",
      "path": "/Web/Command/other.html"
    },
    {
      "title": "一级标题",
      "frontmatter": {},
      "regularPath": "/language/chinese/",
      "relativePath": "language/chinese/README.md",
      "key": "v-fc6220b4",
      "path": "/language/chinese/"
    },
    {
      "title": "Typora常用快捷键",
      "frontmatter": {},
      "regularPath": "/Web/Command/Typora.html",
      "relativePath": "Web/Command/Typora.md",
      "key": "v-72d8270e",
      "path": "/Web/Command/Typora.html",
      "headers": [
        {
          "level": 2,
          "title": "Typora常用快捷键",
          "slug": "typora常用快捷键"
        }
      ]
    },
    {
      "title": "一级标题b",
      "frontmatter": {},
      "regularPath": "/language/chinese/b.html",
      "relativePath": "language/chinese/b.md",
      "key": "v-53c6c9bf",
      "path": "/language/chinese/b.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/language/english/",
      "relativePath": "language/english/README.md",
      "key": "v-e934e4f4",
      "path": "/language/english/"
    },
    {
      "title": "Typora使用",
      "frontmatter": {},
      "regularPath": "/frontWeb/%E5%89%8D%E7%AB%AF.html",
      "relativePath": "frontWeb/前端.md",
      "key": "v-cea56c42",
      "path": "/frontWeb/%E5%89%8D%E7%AB%AF.html"
    },
    {
      "title": "css易混淆属性",
      "frontmatter": {},
      "regularPath": "/Web/Css/01.html",
      "relativePath": "Web/Css/01.md",
      "key": "v-d347a8e6",
      "path": "/Web/Css/01.html",
      "headers": [
        {
          "level": 2,
          "title": "css易混淆属性",
          "slug": "css易混淆属性"
        }
      ]
    },
    {
      "title": "一级标题a",
      "frontmatter": {},
      "regularPath": "/language/chinese/a.html",
      "relativePath": "language/chinese/a.md",
      "key": "v-6140e9c1",
      "path": "/language/chinese/a.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a"
        },
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a-2"
        },
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a-3"
        },
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a-4"
        },
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a-5"
        },
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a-6"
        },
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a-7"
        },
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a-8"
        },
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a-9"
        },
        {
          "level": 2,
          "title": "二级标题a",
          "slug": "二级标题a-10"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "sidebarDepth": 1,
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "前端",
        "items": [
          {
            "text": "常用命令",
            "items": [
              {
                "text": "Typora",
                "link": "/Web/Command/Typora"
              },
              {
                "text": "其他",
                "link": "/Web/Command/other"
              }
            ]
          },
          {
            "text": "学习记录",
            "items": [
              {
                "text": "《Css》",
                "link": "/Web/Css/01"
              },
              {
                "text": "《Javascript》",
                "link": "/Web/Javascript/01"
              },
              {
                "text": "《Vue》",
                "link": "/Web/Javascript/01"
              },
              {
                "text": "《React》",
                "link": "/Web/Javascript/01"
              },
              {
                "text": "《Weex》",
                "link": "/Web/Javascript/01"
              },
              {
                "text": "《ReactNative》",
                "link": "/Web/Javascript/01"
              },
              {
                "text": "《NodeJs》",
                "link": "/Web/Javascript/01"
              }
            ]
          }
        ]
      },
      {
        "text": "后端",
        "items": [
          {
            "text": "教程",
            "items": [
              {
                "text": "《Java》",
                "link": "/Web/Command/Typora"
              },
              {
                "text": "《Php》",
                "link": "/Web/Command/Typora"
              },
              {
                "text": "《Python》",
                "link": "/Web/Command/Typora"
              },
              {
                "text": "《Mysql》",
                "link": "/Web/Command/Typora"
              }
            ]
          },
          {
            "text": "部署",
            "items": [
              {
                "text": "《Docker》",
                "link": "/Web/Command/Typora"
              }
            ]
          }
        ]
      },
      {
        "text": "博客",
        "link": "/frontWeb/前端"
      },
      {
        "text": "GitHub地址",
        "link": "https://github.com/OBKoro1"
      }
    ],
    "sidebar": "auto"
  }
}